 # Exercise 3. - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)

Check out [Alcohol Consumption Exercises Video Tutorial](https://youtu.be/az67CMdmS6s) to watch a data scientist go through the exercises


### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'

df = pd.read_csv(url)

### Step 3. Assign it to a variable called drinks.

In [ ]:
drinks = df
drinks.head()

### Step 4. Which continent drinks more beer on average?

In [ ]:
gb = drinks.groupby('continent').agg({
    'beer_servings' : 'mean'
})
gb.sort_values('beer_servings')

### Step 5. For each continent print the statistics for wine consumption.

In [ ]:
gb = drinks.groupby('continent').agg({
    'wine_servings' : 'describe'
})

In [19]:
gb

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 6. Print the mean alcohol consumption per continent for every column

In [ ]:
gb = drinks.groupby('continent').mean(numeric_only=True)

In [ ]:
gb

### Step 7. Print the median alcohol consumption per continent for every column

In [ ]:
gb = drinks.groupby('continent').median(numeric_only=True)

In [ ]:
gb

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [20]:
drinks.groupby('continent').spirit_servings.agg(['mean', 'min', 'max'])

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302